-- ESTETICA

-- DUENIO

-- MASCOTA

-- SUPERVISOR

-- SUPERVISAR

-- ESTILISTA

-- VETERINARIOS
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('EACL660439MNEZZZ83',119,'Chelsie','Firbank','Lossman','Coahuila De Zaragoza','Village Green',2854,81107,11501.25,'1989-10-07','Female',25,'EAVN6004305E1','8:47','19:40');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('UOIP521729MSPVZZN3',198,'Catlin','Furniss','Petworth','Jalisco','Talisman',9,63836,12510.47,'1991-07-08','Female',10,'DODL450531RT8','9:12','19:55');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('SUHV141318MZSQZZ98',149,'Arny','Phillip','Pinks','Coahuila De Zaragoza','Jenifer',1990,43714,21769.88,'1997-10-26','Male',19,'LOUE941729SNN','8:25','17:47');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('RINR770722MNEXZV56',66,'Sandro','Kowal','Czaple','Guerrero','Sage',40118,02831,28352.34,'1986-06-23','Male',21,'HIDC401934T1V','8:57','18:40');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('WUTD930713HVZZSS70',75,'Hannie','Jess','Luetchford','Chiapas','Annamark',86251,58527,29109.0,'2003-08-18','Female',22,'YOSQ661829W89','8:29','17:55');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('YEQU690503MZSSZTK4',126,'Galvan','Bartlam','Dulen','Coahuila De Zaragoza','Mariners Cove',266,87154,18893.46,'1983-11-14','Male',8,'COAZ75122535Z','9:40','17:43');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('AOJO510733HNEZZXA1',93,'Willdon','Duns','Gallally','Oaxaca','Macpherson',8449,56152,25983.02,'2000-05-19','Male',11,'EOHC551106LZQ','8:32','17:02');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('UOYT070933HNEQVSE2',161,'Oliver','Fluger','Flintiff','Veracruz Llave','Lawn',19,28701,15792.45,'1985-09-21','Male',5,'XUSF770031DJ9','9:21','18:34');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('YOPM130713HYNZZXU5',129,'Burnard','Nuemann','Kinnard','Guerrero','Beilfuss',28,10856,21169.43,'1970-01-06','Male',12,'GUYN660438WCY','8:29','19:03');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('HIJP911402HZSXZXU2',155,'Andreas','Mylechreest','Key','Tamaulipas','Lunder',36491,39387,16484.88,'1989-09-08','Male',13,'MOXZ740637WJB','9:39','18:14');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('BUVP350131HYNTZZ38',105,'Chelsy','Sharp','Laxon','Puebla','Rusk',74,78359,26311.06,'1997-05-27','Female',25,'AUZV0108306NW','8:01','19:57');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('FOJI471816MZSZZZI7',200,'Odell','Di Giorgio','Gianullo','Guerrero','Esker',83,33728,24846.21,'1981-08-05','Male',12,'GUJM151224P99','9:08','19:58');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('ZULH420109HNEZZVE1',13,'Sybila','Ruppeli','Flanne','Tamaulipas','Hoepker',8244,72618,11206.5,'1994-09-18','Female',13,'WUER911520Z48','8:00','19:56');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('XASZ351637HNEZZZK8',139,'Darren','Arnolds','Triggs','Chihuahua','Vera',193,64441,12212.97,'1993-07-04','Male',21,'PUZJ920820KKG','8:43','17:15');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('XIXC430414MNEXTZB6',90,'Jarrad','Gricks','Alderwick','Jalisco','Marquette',59,19171,14254.57,'1991-10-31','Male',10,'GUTU220034E94','8:58','19:06');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('XUKF230233HZSZVZ61',137,'Erasmus','Bertelmot','Viveash','Oaxaca','Ruskin',2544,94142,20323.53,'1994-03-23','Male',9,'AIIA021215876','9:29','19:01');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('NEFN670436HNEZZZG5',104,'Cristina','Lahrs','Lugton','San Luis Potosi','Oak Valley',35587,44530,17669.66,'2003-11-05','Female',16,'PUPI3311385I4','9:45','18:27');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('IOUQ641205MTLVZZ45',115,'Angelina','Honacker','Magarrell','Veracruz Llave','Transport',2,35971,16511.89,'1991-02-20','Agender',8,'PURU7011158CV','8:04','18:02');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('PAMU211509HNEVZX35',132,'Nora','McCumesky','Inglesfield','Puebla','Hallows',602,14622,10797.22,'2002-09-11','Female',7,'GODM661233I79','9:42','19:34');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('MIJI170026HNEZVV65',101,'Imogen','Nurcombe','Pymm','Coahuila De Zaragoza','Oak Valley',587,95154,24628.88,'1993-09-16','Female',22,'DOOL630337514','9:01','17:08');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('RUGN390030HNEZZZM2',107,'Alexandre','Cowie','Baxstar','Veracruz Llave','Village',2981,16935,19042.29,'1979-03-12','Male',12,'RIZN51031575G','8:01','17:57');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('VODT030404HNEZXSP3',29,'Udall','Kettles','Wrathall','Tamaulipas','Monument',94,77122,11883.28,'2003-11-17','Male',21,'HUJA980525H63','8:32','18:05');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('VADO910534MZSZXS64',182,'Luigi','Negri','Whitney','Guerrero','Oak Valley',7001,69011,16202.3,'1976-11-22','Male',8,'NUBR240538806','9:07','17:15');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('BIPN710223MZSXZV68',51,'Mala','Gruszczak','Furphy','Tabasco','Fairview',26,26818,18177.13,'2000-10-23','Genderqueer',18,'TUGI6711386K9','8:05','18:30');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('NUVT971230MYNZXSE0',179,'Garek','Hubach','Guidetti','Veracruz Llave','2nd',6,44064,14416.64,'2002-04-26','Male',15,'EOKI73062590X','9:35','18:07');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('YUQX231026HZSRTV99',64,'Lorinda','Vardy','Shergold','Veracruz Llave','Continental',786,75762,25294.99,'1973-11-08','Female',5,'SIML661222G41','9:08','17:14');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('KUOS440933MYNZSZ30',102,'Dillie','Rashleigh','Trevan','Veracruz Llave','Milwaukee',19699,77839,18531.14,'2004-03-16','Male',24,'LUZC011134KOC','9:20','19:51');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('CUQH420825HYNXXZ53',163,'Ronalda','Goodbairn','Stranio','Coahuila De Zaragoza','Spaight',3104,99053,13133.71,'2000-05-06','Female',5,'JUJC571111HI2','9:14','19:47');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('COJA911932MZSZZZR2',128,'Jordan','Backes','Sedgman','Veracruz Llave','Menomonie',525,19249,29287.76,'1979-08-14','Female',4,'BUGD810014YH9','8:30','18:25');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('QULY771005HZSZXX78',154,'Blinni','Beddoes','Spurway','Tabasco','Ohio',442,90962,23021.26,'1994-11-14','Female',21,'GOTB5817398Z1','9:08','17:47');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('YUZK781233MNEVXZ29',110,'Kelvin','Handrick','Bullcock','Guerrero','Anzinger',09,63424,29012.93,'1976-03-02','Male',14,'QOKZ411632I16','9:33','19:02');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('TEUC101905MNEZZZC1',94,'Amelie','Ebbing','Saich','Tamaulipas','Mcbride',63195,24239,21086.87,'1980-12-06','Female',13,'JULW880039V17','8:34','17:13');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('JUFW741407HYNVVZ77',17,'Clair','Percy','Paulus','Jalisco','Sullivan',896,20127,23907.09,'1972-11-18','Male',5,'OUGM2411208T8','8:36','19:48');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('WUDA880026MNEZZS51',42,'Barbaraanne','Bushill','Milsom','Guerrero','Reindahl',837,94507,25849.11,'1983-03-28','Genderqueer',6,'UUBY221625OYO','8:23','19:49');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('IIWM230728MNEZXT21',158,'Eveleen','Lemonby','Fowls','Puebla','Magdeline',247,38150,21310.56,'1982-09-30','Female',2,'HUXS921035506','8:18','18:40');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('SOEJ660722MZSXZX17',192,'Cheston','Webley','Giovanni','Veracruz Llave','Kropf',97467,09385,29324.54,'1978-03-22','Male',14,'VUAL2812353GT','8:04','18:34');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('WUFO991902HYNLXVM2',49,'Ariana','Gerge','Wong','Veracruz Llave','Sundown',1,99223,11583.94,'1998-12-21','Female',20,'TUYA6715310V9','8:26','18:35');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('UUDW121706MNEVSZC7',168,'Fianna','Lundon','Hawlgarth','Guerrero','Loftsgordon',684,05792,13088.48,'1979-04-17','Female',25,'OAKZ570519Z85','8:43','18:34');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('DUDC751320MTSTXT42',60,'Isidore','Petrosian','Bartoloma','Coahuila De Zaragoza','Tony',72352,22562,29822.99,'1994-07-19','Male',21,'VUFR10171208X','9:56','17:11');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('HUFD980108MYNZZT32',194,'Elfrieda','Vinker','Reah','Puebla','Ridge Oak',52,20429,23393.67,'1975-03-08','Female',12,'XUWM701230E13','9:01','19:03');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('NUPT670633HNEZZZB8',95,'Kathy','Chislett','Turvey','Nuevo Leon','Sunbrook',5937,67100,26993.2,'1988-01-22','Female',23,'KUFM411630MN9','9:05','19:19');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('AUYR851331HNEZVVS8',15,'Brad','Rollinshaw','Abbet','Sonora','Bunker Hill',7912,50228,27519.1,'1985-06-05','Male',14,'NIUY7111334R7','8:26','17:06');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('WECH801839HZSZVQD7',91,'Tadeas','Mochan','Brimman','Guerrero','Pepper Wood',6,81461,29803.77,'1972-09-10','Male',12,'AULR5109319GW','8:11','18:15');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('CUZT160439MNEXZZY5',130,'Stirling','Macvey','Nurse','Veracruz Llave','Johnson',182,36852,14073.6,'1997-03-17','Male',24,'LUMD5119386U8','9:16','19:28');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('BIDC380222MNEZZZ00',98,'Larisa','Succamore','Yggo','Nuevo Leon','Declaration',148,26234,14584.88,'1986-08-03','Female',2,'BUTW1209332N5','9:09','18:05');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('EOSQ230739MNEZZTZ5',121,'Dahlia','Gainforth','Barstock','Chihuahua','2nd',26,05955,20699.43,'1970-06-18','Female',7,'VUJZ471133R15','9:32','18:42');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('NOOC401309MSRZVTX4',76,'Sara','Wahncke','Hewins','Sonora','Namekagon',6,54781,16129.45,'2001-11-01','Agender',22,'BUYG3606126D2','8:52','17:55');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('ROKL720633HZSZZZO5',108,'Devora','Jope','Klosa','Veracruz Llave','Fieldstone',8741,31258,29484.18,'1985-08-15','Female',6,'UAID67123113E','9:09','17:13');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('XUMP120639HNEZVZ40',73,'Mikkel','Sappy','Dennert','Coahuila De Zaragoza','Mesta',02,11928,20717.43,'1972-12-29','Male',23,'YUHZ9904129I3','9:05','19:41');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('MUOU370830MVZZTZW9',1,'Tuckie','Boules','Baniard','Veracruz Llave','Shoshone',4,15337,20828.59,'1987-04-04','Male',16,'KAVA271537S38','8:19','18:48');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('LUJY270424MZSZVV63',156,'Agnese','Codrington','Sinkins','Morelos','Farmco',8,00426,12373.19,'1989-11-09','Female',8,'DUED6302219K5','8:36','18:33');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('RUAS291035HNEXVZ68',171,'Thia','Lowsely','Brownsall','Veracruz Llave','Straubel',3866,04471,24769.52,'1980-12-24','Female',4,'YUQK790434031','8:19','17:10');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('XUZH591214MZSVZV67',70,'Clea','Hymers','Browell','Oaxaca','Mariners Cove',01761,38930,10043.1,'1970-02-15','Female',2,'TUEW3213324UU','8:09','17:29');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('GIRI011237MZSZVX04',39,'Starlin','Shaw','Sarl','Morelos','Milwaukee',70,48219,25906.85,'1995-09-29','Non-binary',4,'CUIB711201QGP','9:24','18:19');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('XUSM460325MNEXVZ58',109,'Aida','Finker','Okroy','Jalisco','Redwing',1562,79350,19988.4,'1993-02-07','Female',11,'PIRJ961539MC6','9:20','19:52');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('JEZM171828MNEVZX05',27,'Elisa','McVeagh','Dhennin','Chihuahua','Badeau',464,12078,23919.72,'1999-08-10','Female',24,'CEPR001039B1Q','8:53','18:22');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('TUEB411638HNEZXZ85',2,'Cristal','Lorait','Isaksen','Michoacan De Ocampo','Burning Wood',4,74966,28592.13,'1970-03-30','Female',8,'PUPL851731KRU','9:35','17:41');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('SIIA270122MZSSXZC3',72,'Marten','Jeanel','Bagley','Puebla','Merrick',60178,50999,18262.77,'1977-03-21','Male',6,'JIWK271529J80','9:52','19:27');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('PICS551109HNEVRVE4',18,'Darwin','Brandone','Tortoishell','Chihuahua','Kim',2,10668,27110.52,'2002-10-19','Male',19,'NULF6414319N2','8:44','18:39');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('FULP660639HVZXVTN1',167,'Karel','Thorneloe','Scupham','Chihuahua','Macpherson',86683,70874,10976.24,'1974-03-16','Male',2,'QIFZ300214PU7','8:31','17:04');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('JUUJ351125MNEVXZ72',173,'Elane','Speachley','Beeken','Chihuahua','Gateway',9674,66817,12269.84,'1987-10-06','Bigender',15,'HUQT060234R5M','9:00','17:23');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('OAIL550534HNEZZXW7',78,'Giacomo','Hrinchenko','Cartmill','Oaxaca','Jana',17399,08533,20557.69,'1993-07-24','Male',18,'HOLQ5314316B6','9:46','18:09');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('EUFH551713HNEZZZV2',160,'Zonda','McMeyler','Featherstonhaugh','Tabasco','Commercial',1,29652,11645.29,'1979-07-07','Female',21,'WUZL640033JW4','8:03','19:39');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('DUON810639HYNZTXD4',152,'Seymour','Walsom','Dadson','Guerrero','Holmberg',18078,96920,29919.38,'1995-07-11','Male',13,'MOHM161433J7M','8:05','19:51');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('FUTD791908MZSZZZ64',21,'Dare','Accum','Jenton','Michoacan De Ocampo','Ohio',4202,59092,18915.87,'1980-02-24','Male',7,'LIET4817245C4','8:27','17:53');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('SUBT560436MVZZZXO1',187,'Will','Ferrini','Falls','Chiapas','Heffernan',10,59662,13688.22,'1973-10-12','Male',16,'VOPH6800380PV','9:12','17:42');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('NAMP660137MVZTZZ44',153,'Lorens','Parlour','Dmitrovic','Chiapas','Swallow',62215,94802,12251.59,'1984-10-10','Male',14,'POIP2818337YF','8:50','17:25');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('TEAW160239HZSZXZ39',183,'Dom','Reddin','Torrisi','San Luis Potosi','Vernon',69132,80401,10076.65,'1974-08-22','Male',15,'ZUNO89093490H','9:41','19:05');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('CUHF151321MTSVTXX0',114,'Tad','Pengelley','Gommowe','Veracruz Llave','Ridgeway',30710,90398,26938.52,'1973-09-28','Male',18,'VUAC720703BTZ','9:48','18:13');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('EIUM621138HYNVVX53',144,'Cornelia','Corley','Spoole','Jalisco','Lien',53,59820,11538.91,'1973-03-18','Female',25,'NUPT331836NG8','9:19','19:43');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('FOUO591338MZSXXV64',181,'Rafaellle','Gardner','Da Costa','Nuevo Leon','Brickson Park',52,65998,26735.94,'1995-10-03','Male',23,'ROKR0304318HA','8:53','17:43');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('LUBC001538HZSXZXT4',5,'Drusy','Reasun','Irvin','Michoacan De Ocampo','Morningstar',1,62034,16837.56,'1990-09-25','Genderfluid',22,'LIZQ940031MJS','9:30','18:41');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('CIME801033HNEXZXO3',136,'Jillene','Kingston','Faint','Veracruz Llave','Swallow',993,14987,29836.51,'1974-03-31','Female',14,'MAAK8411176D3','9:51','18:39');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('OUYC600633MZSZZZN4',74,'Dominga','Jorgensen','Dymick','Veracruz Llave','Forest Dale',51614,17465,19096.37,'1983-01-26','Female',15,'QEGA590212T8H','8:07','17:27');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('VAWN080736HVZZTZU0',125,'Zita','Jansson','Abels','Michoacan De Ocampo','Onsgard',97,77572,21708.27,'1972-04-12','Female',2,'JINU790239PN9','9:14','18:04');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('BEFO770330MTLVXZ17',118,'Randolph','Dressel','Madeley','Zacatecas','Columbus',66188,31549,24080.99,'1984-10-10','Male',23,'HOGY32163746N','9:03','19:16');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('EUTH741735MZSXZTP0',172,'Vale','Eastcourt','Counihan','Chihuahua','Golf Course',024,36513,21277.49,'1996-05-18','Female',24,'ROTZ150818R44','8:53','17:24');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('NUOT420119MNEZVX92',199,'Finn','Buckley','Hayler','Puebla','Barnett',2410,75664,18860.76,'1991-12-04','Male',15,'JUTJ3019342Z1','8:07','17:06');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('IIEA820037HNEZZZ86',44,'Ingram','Armal','Roloff','Veracruz Llave','Carpenter',5827,81530,18529.82,'1986-08-04','Male',6,'KILV5206330PF','8:19','19:10');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('ZUME590730MZSXZZ41',87,'Charley','Obray','Vittle','Chiapas','Brown',7723,01190,13676.58,'1976-09-03','Male',23,'VOIM210232SGU','9:43','18:18');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('GOEZ990905MNEXXV98',92,'Xenia','Sturmey','Auston','Puebla','Crowley',48,84770,22358.92,'2003-12-13','Female',8,'OUHT9704319CT','8:13','18:52');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('UORZ971723HVZZXX88',38,'Aurlie','Geertje','Van Niekerk','Tamaulipas','Village Green',9488,04128,13518.7,'1983-10-11','Female',20,'EOHP8810161XZ','8:41','19:17');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('OUSE730730HYNZZT02',26,'Rasla','Cupitt','McMonnies','Chiapas','Melrose',850,47271,13006.48,'2002-05-14','Female',20,'XUSH191831XAA','9:09','17:51');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('PUGW160111HNEXZZ19',196,'Marianna','Weir','Ferencowicz','Guerrero','Emmet',052,25756,21352.61,'1974-10-30','Female',4,'OUJG820136L0V','9:32','19:47');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('AULV601512MZSVZZL1',162,'Filmore','Mcwhinney','Nichols','Guerrero','Moose',04763,71904,27001.0,'1987-06-22','Male',21,'LUHU880824I7H','8:41','19:03');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('COBS800237HZSXVVB2',190,'Willette','Presnail','Worsom','Coahuila De Zaragoza','Fordem',5704,28619,21552.86,'1994-07-27','Female',1,'UUOT3018272OL','8:45','18:15');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('PUAU450116MZSVZZQ1',166,'Morganne','Metzke','Hollows','Oaxaca','Hallows',48381,76477,20853.16,'1998-06-05','Female',25,'FOXH161935A65','9:39','18:41');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('UUBQ670800MYNZTZ08',141,'Michaeline','Akett','Pudner','Michoacan De Ocampo','Elmside',5,49000,26622.33,'1973-01-24','Female',24,'RUBH971130339','8:56','17:09');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('NENI920313HNETZZN8',35,'Brigham','Armall','Carletto','Chiapas','Namekagon',66,32450,19897.64,'1990-07-05','Agender',17,'TULK280923T75','8:36','18:49');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('CUFI100231HNEVZZ28',89,'Hermie','Eriksson','Grangier','Oaxaca','Rusk',94676,12541,10044.33,'1972-06-09','Male',16,'PUMV36072877O','9:47','18:49');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('UIGF981800HVZXVZ56',57,'Celestine','Daley','Bogart','Veracruz Llave','Londonderry',8,63738,28166.39,'1992-09-17','Female',10,'GUZT260301KJ9','8:22','17:07');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('HUWD411511MZSSSXL5',123,'Kaylee','Szimon','Terne','Nuevo Leon','Memorial',25,31255,17839.12,'1991-12-28','Female',12,'WUYC081437N33','9:07','17:29');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('QIEI421613HNETXZ77',185,'Addy','Lomansey','Carletto','Guerrero','Declaration',75995,18920,28297.57,'1972-04-29','Polygender',14,'YOFQ751837VH8','8:16','17:35');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('FAMC101822HNEZXXD1',65,'Tades','Abdey','Carcass','Coahuila De Zaragoza','Westend',21077,14454,26308.69,'1999-05-21','Male',4,'ROXI231820UT5','9:51','17:01');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('EERF251532HTLZSVR1',4,'Emile','Bignold','Cokayne','Tamaulipas','Ridge Oak',805,41205,17652.39,'1976-08-09','Male',18,'AURZ070625DLI','9:59','17:35');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('GUWB160937HZSSXZ77',59,'Dotty','Mullally','Caplen','Veracruz Llave','La Follette',2,96791,15810.2,'1970-09-17','Female',17,'MURG001435QEM','9:45','19:34');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('BUAK100909HNEPVZS7',56,'Nickolas','Terrey','Jancik','Coahuila De Zaragoza','Oak Valley',65623,44185,13945.03,'1994-10-10','Male',9,'QUNS0302307A2','8:59','19:10');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('DUMX230237HNEXXX48',82,'Swen','Stading','Bulcock','Michoacan De Ocampo','Mifflin',2,57334,19681.39,'1972-07-22','Male',16,'NOBD441023U6K','9:50','19:35');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('TAXR990630HNEVZZ39',30,'Cecil','Strete','Liddington','Veracruz Llave','Londonderry',50,26369,16677.18,'1986-02-21','Female',13,'NUEU3517390T4','8:13','17:20');
INSERT INTO mytable(curp,idEstetica,nombreTrabajador,apellidoPaternoTrabajador,apellidoMaternoTrabajador,estadoTrabajador,calleTrabajador,numeroTrabajador,codigoPostalTrabajador,salarioTrabajador,fechaDeNacimientoTrabajador,generoTrabajador,numeroDePacientesActivosTrabajador,rfcTrabajador,horaEntradaTrabajador,horaSalidaTrabajador) VALUES ('CUMJ190813HNEZSX70',106,'Bebe','Blenkhorn','Virgoe','Guerrero','Express',0482,14265,18405.28,'1971-10-26','Female',2,'HIAO471515I5D','8:46','18:53');


-- RECIBO

-- CONSULTAEMEERGENCIA

-- CONSULTANORMAL

-- PRODUCTO

